feat: Update SSH keys to filesystem

diff --git a/.github/workflows/aws_docker_deploy_service.yaml b/.github/workflows/aws_docker_deploy_service.yaml
--- a/.github/workflows/aws_docker_deploy_service.yaml
+++ b/.github/workflows/aws_docker_deploy_service.yaml
@@ -34,8 +34,37 @@ jobs:
 
       - name: Derive SSH public key from private key for the AWS EC2 instance
         run: |
-          OPERATOR_SSH_PUBLIC_KEY=$(ssh-keygen -y -f <(echo "${{ secrets.OPERATOR_SSH_PRIVATE_KEY }}"))
-          echo "TF_VAR_operator_ssh_pub_key=$OPERATOR_SSH_PUBLIC_KEY" >> "$GITHUB_ENV"
+          mkdir -p ~/.ssh
+          PRIVATE_KEY="${{ secrets.OPERATOR_SSH_PRIVATE_KEY }}"
+          PUBLIC_KEY=$(ssh-keygen -y -f <(echo "$PRIVATE_KEY"))
+          
+          if [[ $PUBLIC_KEY == ssh-rsa* ]]; then
+              KEY_TYPE="rsa"
+          elif [[ $PUBLIC_KEY == ssh-dss* ]]; then
+              KEY_TYPE="dsa"
+          elif [[ $PUBLIC_KEY == ssh-ed25519* ]]; then
+              KEY_TYPE="ed25519"
+          elif [[ $PUBLIC_KEY == ssh-ecdsa* ]]; then
+              KEY_TYPE="ecdsa"
+          else
+              echo "Error: Unsupported SSH key type."
+              exit 1
+          fi
+
+          PRIVATE_KEY_FILE="$HOME/.ssh/id_$KEY_TYPE"
+          PUBLIC_KEY_FILE="$HOME/.ssh/id_${KEY_TYPE}.pub"
+
+          echo "$PRIVATE_KEY" > "$PRIVATE_KEY_FILE"
+          chmod 600 "$PRIVATE_KEY_FILE"
+
+          echo "$PUBLIC_KEY" > "$PUBLIC_KEY_FILE"
+          chmod 644 "$PUBLIC_KEY_FILE"
+
+          echo "PRIVATE_KEY_FILE=$PRIVATE_KEY_FILE" >> "$GITHUB_ENV"
+          echo "PUBLIC_KEY_FILE=$PUBLIC_KEY_FILE" >> "$GITHUB_ENV"
+
+          echo "Private and public keys have been stored in $PRIVATE_KEY_FILE and $PUBLIC_KEY_FILE respectively."
+
 
       - name: Set up Terraform Version
         uses: hashicorp/setup-terraform@v2
@@ -67,12 +96,8 @@ jobs:
   
       - name: Copy and execute the service deployment script on the AWS EC2 instance
         run: | 
-          mkdir -p ~/.ssh
-          echo "${{ secrets.OPERATOR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          cat ~/.ssh/id_rsa
-          scp -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./deploy_service.sh ubuntu@${{ env.INSTANCE_PUBLIC_IP }}:~
-          ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ env.INSTANCE_PUBLIC_IP }} 'nohup ~/deploy_service.sh > deploy_service.log 2>&1 &'
+          scp -v -o StrictHostKeyChecking=no -i ${{ vars.PRIVATE_KEY_FILE }} ./deploy_service.sh ubuntu@${{ env.INSTANCE_PUBLIC_IP }}:~
+          ssh -v -o StrictHostKeyChecking=no -i ${{ vars.PRIVATE_KEY_FILE }} ubuntu@${{ env.INSTANCE_PUBLIC_IP }} 'nohup ~/deploy_service.sh > deploy_service.log 2>&1 &'
 
       - name: Summary
         run: |
